name: Build/prepare

on:
  workflow_dispatch:
  push:
    branches:
      - develop

concurrency: ci-${{ github.workflow }}

jobs:
  build-prepare:
    name: Build/prepare
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: apt-get install
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update -y && sudo apt-get install -y snapd rpm snapcraft fakeroot dpkg

      - name: Install Node and Yarn
        uses: actions/setup-node@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 18.11.0
          cache: 'yarn'

      - name: Install Dependecies
        run: yarn install

      - name: Install global lerna
        run: yarn global add lerna

      - name: Building Packages
        run: yarn run build

      - name: Testing
        run: yarn run test

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
