name: Prepare

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build-prepare:
    name: Prepare
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 18.11.0

      - name: Install Yarn
        run: corepack enable |
          corepack prepare yarn@3.5.1 --activate

      - name: Extract cached dependencies
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Update dependencies
        run: corepack yarn --immutable

      - name: Yarn Workspace Tools
        run: yarn plugin import @yarnpkg/plugin-workspace-tools

      - name: Install Dependecies
        run: yarn install

      - name: Building Packages
        run: yarn run build

      - name: Testing
        run: yarn run test

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
