name: Publish

on: push
# on:
#  push:
#    branches:
#      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and YARn
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1

      - name: Install and build
        run: |
          yarn install
          yarn run postinstall
          yarn run build

      - name: Publish releases
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux
