name: Publish

on: push
# on:
#  push:
#    branches:
#      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and YARn
        uses: actions/setup-node@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 16.18.1
      - name: Setup .yarnrc.yml
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn set version 1.22.19
          sleep 5
          cd release/app && yarn set version 1.22.19

      - name: Install and build
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn run postinstall
          yarn run build
          cd release/app && yarn

      - name: Publish releases
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run ci-release